### ISSUE TITLE
Define a system for including Terms and Conditions in the ecosystem metadata schema

### ISSUE THREAD

**Issue by enridaga** [polifonia-project/rulebook#23]
As the summary says, this would allow declaring whether a component can be reused and what are the terms and conditions (e.g. copy, attribution, commercial vs non-commercial, etc...)

**Comment by enridaga** [comment]
Example:
```yaml
---
licence: CC-BY-NC-4.0
t&c: 
  permissions: 
  - use
  duties: 
  - attribute
  prohibitions: 
  - commercial
```
